version: "3.8"

networks:
  steward_rede:
    driver: bridge

volumes:
  steward_volume:

services:
  steward_nginx_proxy:
    image: nginx
    container_name: steward_proxy
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - steward_rede
    volumes:
      - ./docker-config/nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./docker-logs/nginx:/var/log/nginx
    command: /bin/bash -c "envsubst '$${$http_upgrade},$${$host}' < /etc/nginx/conf.d/site.conf> /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - steward_api

  steward_api:
    image: aler/php-fpm:8.2
    container_name: steward_api
    restart: unless-stopped
    networks:
      - steward_rede
    ports:
      - 9000:9000
    volumes:
      - ./docker-logs/aplicacao:/app/storage/logs
      - ./docker-logs/filas:/var/log/steward
      - .:/app
    #logging:
      #driver: json_file

  steward_db:
    image: postgres:13
    container_name: steward_db
    restart: always
    environment:
      POSTGRES_DB: steward
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpass
      TZ: 'America/Fortaleza'
    volumes:
      - steward_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - steward_rede
    #logging:
      #driver: json_file
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "shared_buffers=1GB"

